//
// Get Editing Article.
//
export const GET_EDITING_ARTICLE_REQUESTED = 'GET_EDITING_ARTICLE_REQUESTED';
export const GET_EDITING_ARTICLE_SUCCESS   = 'GET_EDITING_ARTICLE_SUCCESS';
export const GET_EDITING_ARTICLE_FAILED    = 'GET_EDITING_ARTICLE_FAILED';

//
// Edit Editing Article.
//
export const EDIT_EDITING_ARTICLE_REQUESTED = 'EDIT_EDITING_ARTICLE_REQUESTED';
export const EDIT_EDITING_ARTICLE_SUCCESS   = 'EDIT_EDITING_ARTICLE_SUCCESS';
export const EDIT_EDITING_ARTICLE_FAILED    = 'EDIT_EDITING_ARTICLE_FAILED';

//
// Sync Editing Article.
//
export const SYNC_EDITING_ARTICLE_REQUESTED = 'SYNC_EDITING_ARTICLE_REQUESTED';
export const SYNC_EDITING_ARTICLE_SUCCESS   = 'SYNC_EDITING_ARTICLE_SUCCESS';
export const SYNC_EDITING_ARTICLE_FAILED    = 'SYNC_EDITING_ARTICLE_FAILED';

//
// Reflesh Editing Article.
//
export const REFLESH_EDITING_ARTICLE_REQUESTED = 'REFLESH_EDITING_ARTICLE_REQUESTED';
export const REFLESH_EDITING_ARTICLE_SUCCESS   = 'REFLESH_EDITING_ARTICLE_SUCCESS';
export const REFLESH_EDITING_ARTICLE_FAILED    = 'REFLESH_EDITING_ARTICLE_FAILED';